# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-12 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('channel_rss', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rssfeed',
            name='last_modified',
            field=models.DateTimeField(null=True),
        ),
    ]
