# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-17 09:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.IntegerField(verbose_name='Type')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='ActionInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('mime_type', models.CharField(max_length=255, verbose_name='Mime type')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Action')),
            ],
            options={
                'verbose_name': 'Action Input',
                'verbose_name_plural': 'Action Inputs',
            },
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('color', models.CharField(max_length=7, verbose_name='Channel color')),
                ('image', models.CharField(max_length=128, verbose_name='Channel image')),
                ('font_color', models.CharField(max_length=7, verbose_name='Channel Font')),
            ],
            options={
                'verbose_name': 'Channel',
                'verbose_name_plural': 'Channels',
            },
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Action')),
            ],
            options={
                'verbose_name': 'Recipe',
                'verbose_name_plural': 'Recipes',
            },
        ),
        migrations.CreateModel(
            name='RecipeCondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=1024, verbose_name='Condition Value')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe')),
            ],
            options={
                'verbose_name': 'Recipe Condition',
                'verbose_name_plural': 'Recipe Conditions',
            },
        ),
        migrations.CreateModel(
            name='RecipeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_output', models.TextField(verbose_name='Trigger Input text')),
                ('action_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ActionInput')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Recipe')),
            ],
            options={
                'verbose_name': 'Recipe Mapping',
                'verbose_name_plural': 'Recipe Mappings',
            },
        ),
        migrations.CreateModel(
            name='Trigger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trigger_type', models.IntegerField(verbose_name='Type')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel')),
            ],
            options={
                'verbose_name': 'Trigger',
                'verbose_name_plural': 'Triggers',
            },
        ),
        migrations.CreateModel(
            name='TriggerInput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trigger')),
            ],
            options={
                'verbose_name': 'Trigger Input',
                'verbose_name_plural': 'Trigger Inputs',
            },
        ),
        migrations.CreateModel(
            name='TriggerOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('mime_type', models.CharField(max_length=255, verbose_name='Mime type')),
                ('example_value', models.CharField(max_length=1024, verbose_name='Output example')),
                ('trigger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trigger')),
            ],
            options={
                'verbose_name': 'Trigger Output',
                'verbose_name_plural': 'Trigger Outputs',
            },
        ),
        migrations.AddField(
            model_name='recipecondition',
            name='trigger_input',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.TriggerInput'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='trigger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trigger'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='action',
            name='channel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Channel'),
        ),
        migrations.AlterUniqueTogether(
            name='triggeroutput',
            unique_together=set([('trigger', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='triggerinput',
            unique_together=set([('trigger', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='trigger',
            unique_together=set([('channel', 'trigger_type')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipemapping',
            unique_together=set([('recipe', 'action_input')]),
        ),
        migrations.AlterUniqueTogether(
            name='recipecondition',
            unique_together=set([('recipe', 'trigger_input')]),
        ),
        migrations.AlterUniqueTogether(
            name='actioninput',
            unique_together=set([('action', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='action',
            unique_together=set([('channel', 'action_type')]),
        ),
    ]
