# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-23 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_recipe_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='synopsis',
            field=models.CharField(default='', max_length=140, verbose_name='Synopsis'),
        ),
    ]
