from config.keys import keys

# API keys
CONSUMER_KEY = keys['TWITTER']['APP_KEY']
CONSUMER_SECRET = keys['TWITTER']['APP_SECRET']


# Action types
POST_STATUS = 100
POST_IMAGE = 200
UPDATE_PROFILE_IMAGE = 300
SEND_MESSAGE = 400
